(()=>{
const C=window.TavernKeeperCore;
const $=id=>document.getElementById(id);
let exp=null,speed=1,timer=null,preset=C.makePreset('prepared'),renderedLogs=0;
const controls=['hunger','fatigue','morale','health'];
function loadPreset(){preset=C.makePreset($('preset').value);$('hunger').value=preset.hunger;$('fatigue').value=preset.fatigue;$('morale').value=preset.morale;$('health').value=preset.health;$('weapon').value=preset.equipment.weapon||'wood_axe';$('armor').value=preset.equipment.armor||'';$('potion').checked=(preset.supplies.healing_potion||0)>0;refreshSetup();}
function readHero(){const h=C.makePreset($('preset').value);h.hunger=+$('hunger').value;h.fatigue=+$('fatigue').value;h.morale=+$('morale').value;h.health=+$('health').value;h.equipment.weapon=$('weapon').value;h.equipment.armor=$('armor').value||null;h.supplies.healing_potion=$('potion').checked?1:0;C.deriveMoodlets(h);return h;}
function refreshSetup(){const h=readHero();for(const k of controls)$(k+'V').textContent=' '+$(k).value;$('risk').textContent=C.threatAssessment(h);$('heroCard').innerHTML=`<strong>${h.name}</strong><div>${Object.entries(h.stats).map(([k,v])=>`${k[0].toUpperCase()+k.slice(1)} ${v}`).join(' · ')}</div><div>${h.traits.join(' · ')}</div><small>${h.moodlets.join(' · ')||'No moodlets'}</small>`;}
function fmtTime(s){s=Math.floor(s);return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`}
function render(){if(!exp)return;const h=exp.hero,s=exp.summary(),loc=exp.contract.locations[exp.locationId];$('status').textContent=exp.state.toUpperCase();$('hp').textContent=`${Math.round(h.health)}/${h.maxHealth}`;$('gps').textContent=exp.goldRate.toFixed(2);$('gold').textContent=exp.gold.toFixed(1);$('progress').textContent=`${Math.round(exp.objectiveProgress)}%`;$('location').textContent=loc?.name||'Resolved';$('moodlets').textContent=h.moodlets.join(', ')||'None';$('hpBar').style.width=`${h.health/h.maxHealth*100}%`;$('fatigueBar').style.width=`${h.fatigue}%`;$('hungerBar').style.width=`${h.hunger}%`;$('moraleBar').style.width=`${h.morale}%`;
if(exp.log.length!==renderedLogs){$('log').innerHTML=exp.log.map(e=>`<div class="event ${e.type}"><time>${fmtTime(e.time)}</time>${e.text}${e.reasons?.length?`<span class="reasons">Why: ${e.reasons.join(' · ')}</span>`:''}</div>`).join('');$('log').scrollTop=$('log').scrollHeight;renderedLogs=exp.log.length;}
const d=exp.decisionDebug.at(-1);$('debug').textContent=d?JSON.stringify(d,null,2):'No decision yet.';
if(exp.state!=='deployed')renderSummary();}
function renderSummary(){const s=exp.summary(),m=Object.entries(s.materials).map(([k,v])=>`<span>${v} ${C.MATERIAL_NAMES[k]}${v>1?'s':''}</span>`).join('')||'<span>None</span>';$('summaryBody').innerHTML=`<h3>${s.contract}</h3><p><strong>Result: ${s.outcome.toUpperCase()}</strong> — ${s.reason||''}</p><div class="summary-grid"><div>Time<br><strong>${fmtTime(s.time)}</strong></div><div>Areas<br><strong>${s.areasExplored}/${s.totalAreas}</strong></div><div>Enemies<br><strong>${s.enemiesDefeated}</strong></div><div>Progress<br><strong>${s.objectiveProgress}%</strong></div><div>Peak income<br><strong>${s.peakGoldRate.toFixed(2)} g/s</strong></div><div>Total gold<br><strong>${s.totalGold.toFixed(1)}</strong></div><div>Hero<br><strong>${s.heroAlive?'Alive':'Dead'}</strong></div><div>HP<br><strong>${Math.round(s.health)}</strong></div></div><h3>Recovered Materials</h3><div class="materials">${m}</div>`;}
function loop(){if(!exp||exp.state!=='deployed'||speed===0)return;for(let i=0;i<speed;i++)exp.tick(1);render();}
$('preset').addEventListener('change',loadPreset);for(const id of [...controls,'weapon','armor','potion'])$(id).addEventListener('input',refreshSetup);
$('deploy').addEventListener('click',()=>{exp=new C.Expedition({hero:readHero(),seed:+$('seed').value||1,debug:true});renderedLogs=0;$('summaryBody').innerHTML='<p>Expedition in progress…</p>';render();});
document.querySelectorAll('[data-speed]').forEach(b=>b.addEventListener('click',()=>{speed=+b.dataset.speed;document.querySelectorAll('[data-speed]').forEach(x=>x.classList.toggle('active',x===b));}));
$('step').addEventListener('click',()=>{if(exp&&exp.state==='deployed'){exp.tick(1);render();}});$('reset').addEventListener('click',()=>{exp=null;renderedLogs=0;$('status').textContent='READY';$('log').innerHTML='';$('debug').textContent='';window.scrollTo({top:0,behavior:'smooth'});});
loadPreset();timer=setInterval(loop,250);
})();
